### ISSUE TITLE
Matrix Modifier uses plain value rather than hex value for container modification

### ISSUE THREAD

**Issue by alexfalk** [bbc/qtff-parameter-editor#1]
Hello,
when using a value of 10 in qtff-parameter-editor.sh for matrix this does translate to 16 in container metadata.
This is caused by wrong variable in line 362 which uses »newMatrix« but should be »matrixhex«.
All other possible values are translating to correct hex values coincidentally.
Best, Alex

**Comment by mpindoria-cat** [comment]
Hi Alex, thanks for raising this. I have actually left the BBC and any access to make changes to this repo. I don't think anyone is actively checking this, but I will point someone at this issue and hopefully they can push an update. 

Manish
